spring:
  application:
    name: stock-service
server:
  port: 8060
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8083/eureka/
  instance:
    hostname: localhost
    